
INSERT INTO AI_SQL_TEAM_DB.PUBLIC.OCR_TEST_QUALITY_LEVELS_SMALL (DOCUMENT_ID, OCR_TEXT)
VALUES (
    'file1',
    'No statistically significant test article-related increases were observed in the percent of cells with aberrations with BIO-2136518 or BIO-2136520. Additionally, no statistically significant increases in polyploidy or endoreduplication were observed. The aberrations in vehicle and positive control cultures were comparable to acceptable laboratory historical control ranges.BIO-2136518 (Lot No. TA1522461-001) and BIO-2136520 (Lot No. TA1522461-004) were considered negative for inducing structural aberrations in CHO-WBL cells with and without metabolic activation up to 500 µg/mL under the conditions of this test system. Additionally, there were no significant test article-related increases in numerical aberrations (polyploidy or endoreduplication) in BIO-2136518 and BIO-2136520 treated cultures.# 2. INTRODUCTIONThe objective of this in vitro chromosomal aberration assay was to evaluate the ability of BIO-2136518 and BIO-2136520 to induce chromosome aberrations in cultured Chinese hamster ovary (CHO-WBL) cells with and without an exogenous metabolic activation system and with a short or long-term incubation. Chromosome aberrations are caused by the inability of cells to repair breaks in chromosomes caused by a chemical and are often associated with cancer. Therefore, a chromosomal aberration assay is used as an appropriate test for detecting potential mutagens and carcinogens (Preston et al., 1981).');


INSERT INTO AI_SQL_TEAM_DB.PUBLIC.OCR_TEST_QUALITY_LEVELS_SMALL (DOCUMENT_ID, OCR_TEXT)
VALUES (
    'file2',
    'At approximately 24 hours, cells will be harvested by trypsinization; an aliquot will be removed for cytotoxicity assessment. For the aberration assay(s) only, unless otherwise indicated, trypsinized cells will be collected by centrifugation, resuspended in hypotonic solution $(0.075 \mathrm{M} \mathrm{KCl})$ and fixed in at least 1 change of fixative (approximately $3: 1$ methanol:glacial acetic acid mix) before being stored in the refrigerator. Slides will be prepared for only those cultures which are selected by the Study Director for evaluation of chromosomal aberrations. Fixed cells will be washed with fresh fixative prior to slide preparation. The final concentrated cell suspensions will be dropped onto clean, wet glass slides, dried prior to staining with DiffQuik solution at room temperature, and coverslipped. At least 2 slides will be prepared for each culture. Cultures will be discarded following Sponsor approval of the audited draft report.After completion of the testing, a comprehensive, audited draft report containing the information described above will be submitted to the Sponsor. After receipt of any Sponsor comments, a searchable, submission-ready electronic version (PDF) of the final report will be issued. A tabulated data summary following the appropriate format as outlined in the ICH Harmonized Tripartite Guideline, The Common Technical Document for the Registration of Pharmaceuticals for Human Use: Safety - M4S (R2), Nonclinical Overview and Nonclinical Summaries of Module 2, Organisation of Module 4, will be provided at the same time as the Draft and Final Reports as a separate Microsoft Word document. In the absence of ongoing communications and after notification in writing to the Study Sponsor, the Testing Facility reserves the right to finalize, sign and issue the final study report 6 months after issue of the draft. In such an event, all materials will be transferred to the archive. Any subsequent requests for modifications, corrections or additions to the final report will be the subject of a formal report amendment and will incur additional cost.All data, slides, and reports from this study are the property of the Sponsor. Unless otherwise requested by the Sponsor, following the completion of the final study, all raw data, slides, and reports will be maintained by Charles River for a period of at least 3 years in accordance with applicable SOPs. After the requested retention period, the Sponsor will be contacted to determine whether raw data, slides, and reports should be returned to them or retained in a Charles River archive.All data and reports generated by the Test Site will be transferred to a Charles River Laboratories archive. The data collected using Deviation Information Library and reporting files stored on M-Files will be archived at the Charles River Laboratories facility location in Wilmington, MA. Modification of the protocol may be accomplished during the course of this study. However, no changes will be made in the study design without the verbal or written permission of the Sponsor. In the event that the Sponsor verbally requests or approves a change in the protocol, such changes will be made by appropriate documentation in the form of a protocol amendment. All alterations of the protocol and reasons for the modification(s) will be signed by the Study Director.'
);

INSERT INTO AI_SQL_TEAM_DB.PUBLIC.OCR_TEST_QUALITY_LEVELS_SMALL (DOCUMENT_ID, OCR_TEXT)
VALUES (
    'file3',
    '*Highly purified sterile RNAse free water may be used if WFI is unavailable
2. Remove enough Test Article vials (Nom. Conc. $58 \mathrm{mg} / \mathrm{mL}$ ) based on study needs from 2$8^{\circ} \mathrm{C}$ storage and allow warming to room temperature for at least 30 minutes prior to dose solution preparation. Do not use accelerated warming methods.
3. Before opening, invert each vial a minimum of ten times to ensure a homogeneous solution.
4. Under HEPA filtered air and using clean procedures, transfer the required volume of diluent to an appropriately sized container, and then add the required volume of Test Article (Nom. Conc. $58 \mathrm{mg} / \mathrm{mL}$ ) to the diluent. Transfer of solutions may be performed volumetrically using appropriately sized serological pipettes and micropipettes, or by weight. Close and invert the container a minimum of ten times to ensure adequate mixing.
Note: The density of dPBS diluent is approximately $1.004 \mathrm{~g} / \mathrm{cm}^{3}$. Test article and dose formulation density can be estimated by the following formula: Density $\left(\mathrm{g} / \mathrm{cm}^{3}\right)=0.0004$ $\mathrm{g} \cdot \mathrm{mL} / \mathrm{mg} \cdot \mathrm{cm}^{3} \times$ ASO Concentration $(\mathrm{mg} / \mathrm{mL})+1.004 \mathrm{~g} / \mathrm{cm}^{3}$. For example, the estimated density of $58 \mathrm{mg} / \mathrm{mL}$ Test Article is: $0.0004 \times 58+1.004=1.027 \mathrm{~g} / \mathrm{cm}^{3}$.
5. Filter the diluted Dose Formulation through a sterile $0.22 \mu \mathrm{~m}$ PVDF or PES filters into a sterile container, and store at $2-8^{\circ} \mathrm{C}$ if not used on the day of administration.
6. When necessary, remove samples (after filtration) for concentration analysis by UV spectroscopy (A260 nm) and store at $2-8^{\circ} \mathrm{C}$ until ready for analysis, or at ambient conditions if samples are analyzed on the day of preparation.

## D. Instructions for Administration of Dose Formulation:

If stored at $2-8^{\circ} \mathrm{C}$, remove Dose Formulation from cold storage and allow warming to room temperature for at least 30 minutes prior to dosing. Do not use accelerated warming methods.
# Appendix 2 

Biogen, 225 Binney Street, Cambridge, MA 02142 $\cdot$ Phone 781-464-2000 $\cdot$ www.biogen.com

## E. Stability

Based on platform ASO stability, the Test Article is stable at $2-8^{\circ} \mathrm{C}$ when protected from light, with a retest date of two years from the manufacture.
In case of diluted Dose Formulations, an in-use period of 7 days at $2-8^{\circ} \mathrm{C}$ with an additional time out of refrigeration of 24 hours is assigned after opening the Test Article. In-use stability has been established at $0.1 \mathrm{mg} / \mathrm{mL}$ to $58 \mathrm{mg} / \mathrm{mL}$.
Proper aseptic technique must be used to maintain product sterility over the in-use duration.

## F. Compatibility

As a platform, ASOs are compatible with common administration components used for preclinical studies (e.g., glass, polypropylene, polycarbonate, stainless steel, latex-free elastomer) and filters (e.g., PVDF, PES). Positively charged filter membranes, such as those designed to remove endotoxins or other water impurities (e.g., Posidyne ${ }^{\circledR}$, Mustang E ${ }^{\circledR}$ ) should NOT be used. Amber colored glass vials should also NOT be used.'
);

INSERT INTO AI_SQL_TEAM_DB.PUBLIC.OCR_TEST_QUALITY_LEVELS_SMALL (DOCUMENT_ID, OCR_TEXT)
VALUES (
    'file4',
    '# Appendix 1 

## 7. INTRODUCTION

### 7.1. Objective

The objective of this study is to evaluate the potential of the test article to induce chromosome aberrations in Chinese hamster ovary (CHO-WBL) cells with and without an exogenous metabolic activation system and with short- and/or long-term incubations.
The study will be performed in accordance with the U.S. Department of Health and Human Services, Food and Drug Administration, United States Code of Federal Regulations, Title 21, Part 58: Good Laboratory Practice for Nonclinical Laboratory Studies and as accepted by Regulatory Authorities throughout the European Union (OECD Principles of Good Laboratory Practice) and Japan (MHLW) with the following exception.

- Characterization, stability and Conditions of Handling and Use of the test item were performed by the Sponsor or Sponsor subcontractor according to the established SOPs, controls and approved test methodologies to ensure integrity and validity of the results generated; these analyses were not conducted in compliance with the GLP or GMP regulations.
This study is designed in general accordance with the International Council for Harmonisation (ICH) Guideline S2(R1) (09 Nov 2011) and the OECD Guideline Number 473 (29 Jul 2016). This study will also be performed according to the protocol and any amendment(s) and applicable Charles River Standard Operating Procedures (SOPs). Any portion of this study conducted in Canada was performed in accordance with the OECD Principles of Good Laboratory Practice as accepted by Regulatory Authorities throughout the European Union, United States of America (FDA), Japan (MHLW), and other countries that are signatories to the OECD Mutual Acceptance of Data Agreement.


### 7.2. Background

The in vitro mammalian cell assay evaluates the ability of a test article to induce structural changes (chromosomal aberrations) in the genetic material of the cell. Chromosome alterations result from an inability of cells to repair breaks in chromosomes that may be caused by exposure to chemicals or other exogenous agents and are often associated with cancer. Therefore, a chromosomal aberration assay is used as an appropriate test for detecting potential clastogens and carcinogens. CHO-WBL cells have been demonstrated to be sensitive to the clastogenic activity of a variety of chemicals (Preston et al., 1981).
# Appendix 1 

## 8. TEST MATERIAL

### 8.1. Test Material

### 8.1.1. Identification

|  | Test Article 1 | BIO-2136520 ( $62.1 \mathrm{mg} / \mathrm{mL}$, before compounding) | Test Article 2: <br> (after compounding) |
| :--: | :--: | :--: | :--: |
| Identification: | BIO-2136518 | BIO-2136520 | BIO-2136520 |
| Alternate Identification: | BIIB134-ASO; <br> DMPK ASO; ASO | Non compounded BIIB134DMPK ASO_MOLECULE; ASO-linker; DMPK MAL-AH-ASO | Compounded BIIB134-DMPK ASO_MOLECULE; ASOlinker; DMPK MAL-AH-ASO |
| Batch/Lot No.: | TA1522461-001 | TA1522461-004 | N/A |
| Expiration <br> /Retest Date: | 12 Oct 2023 | 26 Jul 2023 | 24 hours after preparation |
| Physical <br> Description: | Liquid Solution | Liquid Solution | Liquid Solution |
| Purity Factor for Analysis: | Not applicable | 0.846 | 0.833 |
| Nominal Concentration: | $58 \mathrm{mg} / \mathrm{mL}$ | $59 \mathrm{mg} / \mathrm{mL}$ | $55 \mathrm{mg} / \mathrm{mL}$ |
| Full Length Product Concentration ${ }^{a}$ : | $57.2 \mathrm{mg} / \mathrm{mL}^{\mathrm{a}, \mathrm{b}}$ | $62.1 \mathrm{mg} / \mathrm{mL}$ <br> (formulated in 2 mM acetate, 0.26 mM sodium chloride) ${ }^{\text {c }}$ | $54.4 \mathrm{mg} / \mathrm{mL}^{\mathrm{a}}$ <br> (formulated in <br> 2 mM acetate, 72 mM sodium chloride) |
| Measurement for Sample Wavelength: | 260 nm | 260 nm | 260 nm |
| Storage <br> Conditions <br> (temperature set to maintain): | $2^{\circ} \mathrm{C}$ to $8^{\circ} \mathrm{C}$ <br> Protected from light (do not use amber bottles) | $-10^{\circ} \mathrm{C}$ to $-30^{\circ} \mathrm{C}$, protected from light (do not use amber bottles) | Set to maintain $-10^{\circ} \mathrm{C}$ to $-30^{\circ} \mathrm{C}$, protect from light (do not use amber bottles) |
| Provided by: | Sponsor | Sponsor | Sponsor |

${ }^{a}$ To be used in calculations
${ }^{\mathrm{b}}$ Full length product concentration formulated in Dulbecco s phosphate buffer saline (dPBS).
${ }^{\text {c }}$ Vial containing 5.2 mL to be compounded with 0.4 mL Compounding Buffer ( 2 mM acetate, 1000 mM sodium chloride) to yield a FLP concentration of $54.4 \mathrm{mg} / \mathrm{mL}$ (formulated in 2 mM acetate, 72 mM sodium chloride); refer to the table below for Compounding Buffer information
# Appendix 1

|   | Compounding Buffer
(Used to compound Test Article 2 [BIO-2136520])  |
| --- | --- |
|  Identification: | 2 mM acetate, 1000 mM sodium chloride, pH 5.3  |
|  Storage Conditions (temperature
set to maintain): | Room temperature  |
|  Lot Number: | EXP-15Aug2022-0036  |
|  Retest Date: | 10 Nov 2022  |
|  Provided by: | Sponsor  |

### 8.1.2. Characteristics

The Sponsor will provide any necessary evaluations related to chemical composition, purity, strength, stability, identity, uniformity and method of synthesis of the test article.

### 8.1.3. Handling Precautions

An SDS may be provided by the Sponsor. It is the responsibility of the Sponsor to notify the testing facility of any special handling requirements of the test article. Otherwise, routine safety precautions will be followed.

Minimum safety requirements include safety glasses, impervious gloves, and laboratory wear. An SDS shall also be available for all chemical entities utilized in the conduct of this study.

### 8.1.4. Test Material Retention and Disposition

Due to the study duration, a retention (reserve) sample of the test article will not be collected. Any remaining unopened test article will be returned to the Sponsor.

### 8.2. Test Material Formulations

The test article will be compounded in 2 mM acetate, 1000 mM NaCl , pH 5.3 immediately before preparing dosing formulations using the following instructions: Vial containing 5.2 mL to be compounded with 0.4 mL Compounding Buffer ( 2 mM acetate, 1000 mM sodium chloride) to yield a FLP concentration of $54.4 \mathrm{mg} / \mathrm{mL}$ (formulated in 2 mM acetate, 72 mM sodium chloride).

Dosing formulations will be prepared under a laminar flow hood using clean procedures. Dosing formulations will be prepared at appropriate concentrations to meet concentration requirements as per Sponsor instructions.

Test Article 1 dose formulations will be filtered via a $0.22 \mu \mathrm{~m}$ Polyvinylidene fluoride filter (PVDF) syringe into clear colorless glass vials wrapped in aluminum foil (no amber glass) and stored (if needed) in a refrigerator set to maintain $4^{\circ} \mathrm{C}$, protected from light until dispensed for dosing, use within 7 days of preparation. Test Article 2 (after compounding) dose formulations will be filtered via a $0.22 \mu \mathrm{~m}$ Polyvinylidene fluoride filter (PVDF) syringe into clear colorless glass vials wrapped in
# Appendix 1 

aluminum foil (no amber glass) and stored (if needed) in a freezer set to maintain $-20^{\circ} \mathrm{C}$, protected from light until dispensed for dosing, used within 3 days of preparation.
If needed, aliquots will be removed from the refrigerator or freezer and allowed to warm to room temperature for at least 30 minutes before experimental initiation. Do not use accelerated warming methods.

Prior to dosing each group, aliquots will be inverted a minimum of ten times to ensure a homogenous solution.

A correction factor will not be used during the formulation preparation. The method of preparation will be documented in the raw data and presented in the final report.'
);


INSERT INTO AI_SQL_TEAM_DB.PUBLIC.OCR_TEST_QUALITY_LEVELS_SMALL (DOCUMENT_ID, OCR_TEXT)
VALUES (
    'biogen5',
    '| Test Article 2 | low, mid, high | Dosing <br> container | 4 | 2 | 2 | 0.5 |

Quadruplicate samples ( 0.5 mL , each) of the vehicle and low-, mid-, and high-dose test article concentrations from the aberration assay will be collected for concentration analysis. Stability testing will be provided by the Sponsor. If an even number of test article concentrations are prepared, the higher of the mid-dose concentrations will be sampled. Both sets of test article 1 dose formulations will be stored in temperature set to maintain $4^{\circ} \mathrm{C}$, protected from light in vials wrapped in foil. Both sets of test article 2 dose formulations will be stored at $-10^{\circ} \mathrm{C}$ to $30^{\circ} \mathrm{C}$, protected from light in vials wrapped in foil. Both sets of test article 2 formulations will be shipped (in separate boxes) on dry ice, and both set of test item 1 formulations will be shipped (in separate boxes) on refrigerated packs, via overnight on a Monday, Tuesday, Wednesday or Thursday to:
Charles River Laboratories Montreal ULC
Senneville Site
22022 Transcanada Highway
Senneville, Quebec Canada H9X 3R3
Tel: $1514-6300-8200$
C/o Custom Broker: Expeditors Canada, Inc
To the ATTENTION of: Anna Petruccio (Study No. 00793242_Reference no. 2200043)
The recipient will be notified in advance of the shipment. The test article 1 formulation samples received at the Test Site will be stored refrigerated, set to maintain $4^{\circ} \mathrm{C}$, protected from light
# Appendix 1 

and the test article 2 formulation samples received at the Test Site will either be stored at $-10^{\circ} \mathrm{C}$ to $-30^{\circ} \mathrm{C}$, protected from light, or processed upon receipt.
Dose formulations will be analyzed by the Test Site in accordance with applicable SOPs and GLP regulations using a validated method (Study Nos. 1805589 and 1804787). The formulation samples will be analyzed by a UV-Vis spectrophotometric analytical method methods, AP.2200043.SL1.xx and AP.2200043.SL2.xx, where "xx" is the version number. Draft results will be transmitted to the Study Director and a summary report signed by the Principal Investigator and Test Site Quality Assurance will be provided for inclusion in the final study report.
Acceptance Criteria: Mean sample concentration of $\pm 10 \%$ of theoretical concentration. Individual sample concentration of $\pm 15 \%$.

## 9. MATERIALS AND METHODS

### 9.1. Vehicle Control Material

The vehicle control, Dulbecco s Phosphate Buffer Saline[(dPBS), Manufacturer and Catalog Number: Gibco (No. 14190)], will be stored at $19^{\circ} \mathrm{C}$ to $25^{\circ} \mathrm{C}$. The volume of vehicle in control cultures will not exceed $10 \%$ of total volume.

### 9.2. Positive Control Materials

The positive controls to be used are mitomycin C (MMC; CAS No. 50-07-7), a direct-acting clastogen that does not require metabolic activation, and cyclophosphamide monohydrate (CP; CAS No. 6055-19-2), a metabolism-dependent clastogen.
Neat positive controls are stored at $2^{\circ} \mathrm{C}$ to $8^{\circ} \mathrm{C}$. Positive controls are dissolved in DMSO, stored frozen in aliquots at $-60^{\circ} \mathrm{C}$ to $-80^{\circ} \mathrm{C}$ and thawed immediately before use. All unused material will be discarded.
Analytical evaluations of the positive controls are not required as the chemical characteristics and stability of the positive controls are on file with the manufacturer and can be tracked in the raw data by the manufacturers  lot number.

### 9.3. Test System

CHO-WBL cells were originally obtained from the Genetic Toxicology Laboratory at Pfizer, Inc. (Groton, CT) and are stored cryopreserved in liquid nitrogen. The cells have been tested to ensure that they are free of mycoplasma contamination and their karyotype has been checked to ensure a modal chromosome number of 21 .

### 9.4. Media and Cell Culture Conditions

Duplicate cultures will be prepared by seeding with $0.6-0.8 \times 10^{6} \mathrm{CHO}$-WBL cells per $75 \mathrm{~cm}^{2}$ flask in McCoy s medium supplemented with a final concentration of $10 \%(\mathrm{v} / \mathrm{v})$ heat-inactivated
# Appendix 1 

fetal bovine serum (FBS), 2 mM L glutamine, and 100 units $/ \mathrm{mL}$ penicillin and $100 \mu \mathrm{~g} / \mathrm{mL}$ streptomycin (CHO-WBL growth media). All cultures will be incubated at $36^{\circ} \mathrm{C}$ to $38^{\circ} \mathrm{C}$ in vented flasks in a humidified atmosphere of $4 \%$ to $6 \% \mathrm{CO}_{2}$ for approximately 24 hours.

## 9.5. S9 Metabolic Activation System

The $9000 \times g$ liver supernatant fraction (S9) from phenobarbital/5,6-benzoflavone-treated male rats, glucose-6-phosphate and $\mathrm{MgCl}_{2}-\mathrm{KCl}$ in 0.1 M phosphate buffer (Regensys " A "), and lyophilized nicotinamide adenine dinucleotide phosphate (NADP; Regensys " B ") are obtained from Molecular Toxicology, Inc. (Boone, NC). These reagents will be combined to create the metabolic activation mixture (S9), maintained at $2^{\circ} \mathrm{C}$ to $8^{\circ} \mathrm{C}$ or on ice prior to use, on the day of testing.

Regensys "A" and Regensys "B" are received in pre-measured aliquots and stored refrigerated $\left(2^{\circ} \mathrm{C}\right.$ to $\left.8^{\circ} \mathrm{C}\right)$ and frozen $\left(-10^{\circ} \mathrm{C}\right.$ to $\left.-30^{\circ} \mathrm{C}\right)$, respectively. Prior to use, the appropriate aliquot(s) of Regensys " B " will be removed from storage and maintained at ambient temperature. Regensys "A" will be maintained at $2^{\circ} \mathrm{C}$ to $8^{\circ} \mathrm{C}$ or on ice. Regensys " A " will be used to reconstitute an appropriate aliquot of Regensys " B ". The Regensys A and B solution will be mixed prior to formulating the S9 mixture. The S9 mixture will contain $1.5 \%$ S9 and $6 \%$ combined Regensys solution in CHO-WBL growth media.

### 9.6. Range-finding Cytotoxicity Assay

A solubility test may be conducted prior to cytotoxicity testing to determine the highest soluble concentration in the vehicle. For range-finding cytotoxicity testing, single cultures will be exposed to the vehicle and BIO-2136518, and BIO2136520 target concentrations of $0.977,1.95$, $3.91,7.81,15.6,31.3,62.5,125,250$, and $500 \mu \mathrm{~g} / \mathrm{mL} \mu \mathrm{g} / \mathrm{mL}$ using the treatment conditions outlined in Section 9.8.1 and Section 9.8.2. Concentrations may be adjusted based on solubility limitations. Any alternate dose levels will be specified in the raw data via memo or email from the Study Director and reported.

All cultures will be examined visually for signs of cytotoxicity (i.e., visible cell abnormalities), pH change (as indicated by change in the color of the media) and precipitates at the time of dosing, at the end of the 4 -hour treatment (at wash), and prior to harvest. Treatments will be terminated as described in Section 9.9. Slides will only be prepared for the range-finding assay if requested by the Study Director. This request will be documented in the raw data via memo or email or other similar correspondence. Cytotoxicity will be evaluated as described in Section 9.10.

### 9.7. Chromosome Aberration Assay

For the chromosome aberration assay, duplicate cultures will be exposed to the vehicle, 2 concentrations of positive control, and the 5 highest concentrations of BIO-2136518 and BIO2136520 tested in the range-finding assay using the treatment conditions outlined in Section 9.8.1 and Section 9.8.2. Any alternate dose levels will be specified by amendment.
# Appendix 1 

All cultures will be examined visually for signs of cytotoxicity (i.e., visible cell abnormalities), pH change (as indicated by change in the color of the media) and precipitates at the time of dosing, at the end of the 4 -hour treatment (at wash), and prior to harvest. Treatments will be terminated and slides will be prepared as described in Section 9.9. Cytotoxicity will be evaluated as described in Section 9.10. Concentrations chosen for chromosome aberration assessment will be selected based on cytotoxicity in this assay as described in Section 9.11. At the discretion of the Study Director, additional duplicate cultures may be tested if cytotoxicity in this assay is not optimal.

### 9.8. Treatment of Test System with Test or Control Material

CHO-WBL cells have a 12- to 14-hour cycling time (Galloway et al., 1994); therefore, a single harvest time of approximately 24 hours will be used. Treatment conditions are 4 hours with and without metabolic activation and 24 hours without activation. Positive control (mitomycin C at 0.50 and $0.75 \mu \mathrm{~g} / \mathrm{mL}$ ( 4 hour) or 0.050 and $0.10 \mu \mathrm{~g} / \mathrm{mL}$ ( 24 hour) in cultures without activation and cyclophosphamide at 5.0 and $7.5 \mu \mathrm{~g} / \mathrm{mL}$ in cultures with activation) and vehicle control cultures will also be included in all 3 treatment conditions, unless otherwise indicated.

### 9.8.1. Assay without Metabolic Activation

Approximately 1 day after seeding cultures, the cells will be treated with vehicle, test article and the appropriate positive control article and returned to the incubator at $36^{\circ} \mathrm{C}$ to $38^{\circ} \mathrm{C}$ for an exposure period of approximately 4 hours. Another set of cultures will be treated and exposed for approximately 24 hours. After exposure, the 4 -hour cultures will be washed with Dulbecco s phosphate buffered saline (DPBS) or CHO-WBL growth media to remove the vehicle, test article and positive control articles. CHO-WBL growth media will be added and the cultures will be returned to the incubator. Colcemid ${ }^{\circledR}(0.1 \mu \mathrm{~g} / \mathrm{mL})$ will be added for the final 1.5 to 2.5 hours to arrest cells in metaphase. The cultures will be harvested at approximately 24 hours as per Section 9.9 and cytotoxicity will be evaluated as per Section 9.10.

### 9.8.2. Assay with Metabolic Activation

Approximately 1 day after seeding cultures, the cells will be treated with vehicle, test article and the appropriate positive control article and returned to the incubator at $36^{\circ} \mathrm{C}$ to $38^{\circ} \mathrm{C}$ for an exposure period of approximately 4 hours in medium with an exogenous metabolic activation system (S9). After exposure, the 4 -hour cultures will be washed with DPBS or CHO-WBL growth media to remove the vehicle, test article, and positive control articles. CHO-WBL growth media will be added and the cultures will be returned to the incubator. Colcemid ${ }^{\circledR}$ $(0.1 \mu \mathrm{~g} / \mathrm{mL})$ will be added for the final 1.5 to 2.5 hours to arrest cells in metaphase. The cultures will be harvested at approximately 24 hours as per Section 9.9 and cytotoxicity will be evaluated as per Section 9.10.

### 9.8.3. Identification of Culture Flasks

Each culture flask will be identified with the following, at a minimum:
# Appendix 1 

- The study number
- The assay date (date of dosing)
- The vehicle, positive control or test article names and/or concentration (if applicable)
- Length of treatment (i.e., 4- or 24-hour), this may be abbreviated to just the number of hours without the label hour
- Presence or absence of metabolic activation:
- Without metabolic activation: Minus sign ( - )
- With metabolic activation: Plus sign (+)


## 9.9. Termination of Treatment and Slide Preparation

At approximately 24 hours, cells will be harvested by trypsinization; an aliquot will be removed for cytotoxicity assessment. For the aberration assay(s) only, unless otherwise indicated, trypsinized cells will be collected by centrifugation, resuspended in hypotonic solution $(0.075 \mathrm{M} \mathrm{KCl})$ and fixed in at least 1 change of fixative (approximately $3: 1$ methanol:glacial acetic acid mix) before being stored in the refrigerator. Slides will be prepared for only those cultures which are selected by the Study Director for evaluation of chromosomal aberrations. Fixed cells will be washed with fresh fixative prior to slide preparation. The final concentrated cell suspensions will be dropped onto clean, wet glass slides, dried prior to staining with DiffQuik solution at room temperature, and coverslipped. At least 2 slides will be prepared for each culture. Cultures will be discarded following Sponsor approval of the audited draft report.

### 9.9.1. Identification of Slides

Each slide will be identified with the following, at a minimum:

- The study number
- The assay date (date of dosing)
- Length of treatment (i.e., 4- or 24-hour; abbreviated to just the number)
- Presence or absence of metabolic activation:
- Without metabolic activation: Minus sign ( - )
- With metabolic activation: Plus sign (+)
- Vehicle (VC), positive control name and concentration, or test article concentration or coded slide number
- Culture replicate (designated as A or B), as applicable
- Slide replicate (designated as 1 or 2 )
# Appendix 1 

### 9.10. Cytotoxicity and Test System Evaluations

Cytotoxicity results will be used to identify the appropriate concentrations for analysis of chromosome aberrations.

Cytotoxicity will be assessed by reduction in relative population doubling using cell viability data obtained from Coulter counts or hemacytometer. In the event that cell viability data are insufficient, the reduction in mitotic index may also be evaluated by counting the number of mitotic cells in at least 1000 cells from each culture. Cells treated with test article or positive control will be compared with vehicle control cultures (see Appendix 1).

### 9.11. Chromosome Aberration Evaluation

The concentrations (at least 3) chosen for evaluating chromosome aberrations will be based on cytotoxicity results obtained from the cytotoxicity evaluation (Section 9.10). The highest concentration selected for chromosome aberration evaluation will be the concentration producing approximately $50-60 \%$ cytotoxicity, concentrations where precipitates are observed, or the highest concentration tested. Chromosome aberrations will be scored from duplicate cultures, unless otherwise directed by the Study Director. At least 3 test article concentrations, 1 positive control concentration, and the vehicle will be scored for chromosome aberrations in each treatment condition. The test article concentrations to be scored for chromosome aberrations will be documented in the raw data.

For control of bias, the slides will be randomized and coded by an individual not involved with the scoring process prior to analysis. Structural chromosomal aberrations will be analyzed from a total of at least 300 metaphase cells per treatment ( 150 cells from each culture) or $\geq 50$ aberrant cells from each test article concentration or control, when available. A standard form will be used to record chromatid breaks, deletions, exchanges, rings, dicentrics, and other changes in chromosomal morphology. In addition, chromatid or chromosome gaps and uncoiled chromosomes will be recorded but not included in the aberrations frequency because they are not considered to represent true breaks. A list of the calculations used and definitions of aberrations can be found in Appendix 1 and Section 1., respectively. Numerical aberrations (endoreduplication and polyploidy) will be evaluated from a total of 400 cells per treatment ( 200 cells from each culture).

### 9.12. Data Presentation

Data will be summarized in tables showing cytotoxicity, percent polyploidy, percent endoreduplication, number of cells analyzed, frequencies of aberrations per cell, and percentages of cells with aberrations.');